version: '2'
services:
  mongodb:
    image: mongo
    ports:
      - "31300:27017"
    volumes:
      - /data/mongodb:/data/db
    hostname: mongodb
    container_name: mongodb
    restart: always

  spider:
    build: porn
    container_name: spider
    restart: always
    depends_on:
      - mongodb
    links:
      - mongodb
    restart: always